azure:
  settings_linux:
    timeoutInMinutes: 1
  settings_osx:
    timeoutInMinutes: 1
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_build_tool: conda-build+conda-libmamba-solver
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  timeout_minutes: 720
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
  linux_aarch64: default
test: native_and_emulated
